/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bryanplay_MediaPlayer */

#ifndef _Included_bryanplay_MediaPlayer
#define _Included_bryanplay_MediaPlayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bryanplay_MediaPlayer
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_bryanplay_MediaPlayer_init
  (JNIEnv *, jobject);

/*
 * Class:     bryanplay_MediaPlayer
 * Method:    set_video_panel_x
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_bryanplay_MediaPlayer_set_1video_1panel_1x
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bryanplay_MediaPlayer
 * Method:    add_media
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT jint JNICALL Java_bryanplay_MediaPlayer_add_1media
  (JNIEnv *, jobject, jstring);

/*
 * Class:     bryanplay_MediaPlayer
 * Method:    play_playlist
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_bryanplay_MediaPlayer_play_1playlist
  (JNIEnv *, jobject);

/*
 * Class:     bryanplay_MediaPlayer
 * Method:    refresh_current_media
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_bryanplay_MediaPlayer_refresh_1current_1media
  (JNIEnv *, jobject);

/*
 * Class:     bryanplay_MediaPlayer
 * Method:    player_pause
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_bryanplay_MediaPlayer_player_1pause
  (JNIEnv *, jobject);

/*
 * Class:     bryanplay_MediaPlayer
 * Method:    play_next
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_bryanplay_MediaPlayer_play_1next
  (JNIEnv *, jobject);

/*
 * Class:     bryanplay_MediaPlayer
 * Method:    play_previous
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_bryanplay_MediaPlayer_play_1previous
  (JNIEnv *, jobject);

/*
 * Class:     bryanplay_MediaPlayer
 * Method:    player_stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_bryanplay_MediaPlayer_player_1stop
  (JNIEnv *, jobject);

/*
 * Class:     bryanplay_MediaPlayer
 * Method:    play_item
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_bryanplay_MediaPlayer_play_1item
  (JNIEnv *, jobject, jint);

/*
 * Class:     bryanplay_MediaPlayer
 * Method:    set_volume
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_bryanplay_MediaPlayer_set_1volume
  (JNIEnv *, jobject, jint);

/*
 * Class:     bryanplay_MediaPlayer
 * Method:    get_volume
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_bryanplay_MediaPlayer_get_1volume
  (JNIEnv *, jobject);

/*
 * Class:     bryanplay_MediaPlayer
 * Method:    set_mute
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_bryanplay_MediaPlayer_set_1mute
  (JNIEnv *, jobject);

/*
 * Class:     bryanplay_MediaPlayer
 * Method:    is_media_seekable
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_bryanplay_MediaPlayer_is_1media_1seekable
  (JNIEnv *, jobject);

/*
 * Class:     bryanplay_MediaPlayer
 * Method:    seek_time
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_bryanplay_MediaPlayer_seek_1time
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bryanplay_MediaPlayer
 * Method:    get_media_length
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_bryanplay_MediaPlayer_get_1media_1length
  (JNIEnv *, jobject);

/*
 * Class:     bryanplay_MediaPlayer
 * Method:    set_play_mode
 * Signature: (S)V
 */
JNIEXPORT void JNICALL Java_bryanplay_MediaPlayer_set_1play_1mode
  (JNIEnv *, jobject, jshort);

/*
 * Class:     bryanplay_MediaPlayer
 * Method:    get_current_title
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_bryanplay_MediaPlayer_get_1current_1title
  (JNIEnv *, jobject);

/*
 * Class:     bryanplay_MediaPlayer
 * Method:    get_current_artist
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_bryanplay_MediaPlayer_get_1current_1artist
  (JNIEnv *, jobject);

/*
 * Class:     bryanplay_MediaPlayer
 * Method:    get_current_album
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_bryanplay_MediaPlayer_get_1current_1album
  (JNIEnv *, jobject);

/*
 * Class:     bryanplay_MediaPlayer
 * Method:    get_current_track_number
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_bryanplay_MediaPlayer_get_1current_1track_1number
  (JNIEnv *, jobject);

/*
 * Class:     bryanplay_MediaPlayer
 * Method:    get_current_artwork_url
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_bryanplay_MediaPlayer_get_1current_1artwork_1url
  (JNIEnv *, jobject);

/*
 * Class:     bryanplay_MediaPlayer
 * Method:    get_current_genre
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_bryanplay_MediaPlayer_get_1current_1genre
  (JNIEnv *, jobject);

/*
 * Class:     bryanplay_MediaPlayer
 * Method:    get_current_date
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_bryanplay_MediaPlayer_get_1current_1date
  (JNIEnv *, jobject);

/*
 * Class:     bryanplay_MediaPlayer
 * Method:    get_current_publisher
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_bryanplay_MediaPlayer_get_1current_1publisher
  (JNIEnv *, jobject);

/*
 * Class:     bryanplay_MediaPlayer
 * Method:    get_current_copyright
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_bryanplay_MediaPlayer_get_1current_1copyright
  (JNIEnv *, jobject);

/*
 * Class:     bryanplay_MediaPlayer
 * Method:    get_current_url
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_bryanplay_MediaPlayer_get_1current_1url
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
